export const ingrdient = [
    { title: 'خبز بيتا', type: 'unité' },
    { title: 'بطيخ', type: 'unité' },
    { title: 'بذور الشمر', type: 'unité' },
    { title: 'سمك أبو سيف', type: 'unité' },
    { title: 'الثلج المسحوق', type: 'unité' },
    { title: 'لفت', type: 'unité' },
    { title: 'الماء المثلج', type: 'unité' },
    { title: 'الشاي الأخضر العادي', type: 'unité' },
    { title: 'سمك السردين', type: 'unité' },
    { title: 'قرع', type: 'unité' },
    { title: 'شوفان', type: 'unité' },
    { title: 'مشمش', type: 'unité' },
    { title: 'بروكلي', type: 'unité' },
    { title: 'معكرونة أصداف', type: 'unité' },
    { title: 'بذور شيا', type: 'unité' },
    { title: 'بذور اليقطين المحمص', type: 'unité' },
    { title: 'اليقطين', type: 'unité' },
    { title: 'العدس الأحمر', type: 'unité' },
    { title: 'كوريزو', type: 'unité' },
    { title: 'حبات الهيل', type: 'pièce' },
    { title: 'شوكولاتة سوداء مبشورة', type: 'unité' },
    { title: 'أوراق البريك', type: 'unité' },
    { title: 'مرقاز', type: 'unité' },
    { title: 'نصف رأس ثوم', type: 'unité' },
    { title: 'موس بالشوكولاتة السوداء', type: 'unité' },
    { title: 'نجمة اليانسون', type: 'unité' },
    { title: 'نشاء', type: 'unité' },
    { title: 'نعناع مفروم', type: 'unité' },
    { title: 'نعناع مقطع', type: 'unité' },
    { title: 'نوتيلا', type: 'unité' },
    { title: 'هريسة', type: 'unité' },
    { title: 'هريسة ناظور الوطن القبلي', type: 'unité' },
    { title: 'ورق الحبق', type: 'unité' },
    { title: 'ورق نعناع مقطع', type: 'unité' },
    { title: 'ورق الغار', type: 'unité' },
    { title: 'ورقة سبناخ', type: 'unité' },
    { title: 'ورقة خس', type: 'unité' },
    { title: 'ياغورط طبيعي', type: 'unité' },
    { title: 'موس بالشوكولاتة', type: 'unité' },
    { title: 'موس بالشوكولاتة البيضاء', type: 'unité' },
    { title: 'موس النوتيلا', type: 'unité' },
    { title: 'موس الكاكاو', type: 'unité' },
    { title: 'موس الفستق', type: 'unité' },
    { title: 'موس الفانيليا', type: 'unité' },
    { title: 'موس الزبادي', type: 'unité' },
    { title: 'موس الشوكولاتة', type: 'unité' },
    { title: 'موس الجبن الكريمي', type: 'unité' },
    { title: 'موز', type: 'unité' },
    { title: 'منتج CandyS', type: 'unité' },
    { title: 'ملون غذائي', type: 'unité' },
    { title: 'ملفوف أحمر', type: 'unité' },
    { title: 'ملفوف أبيض', type: 'unité' },
    { title: 'ملح خشين', type: 'unité' },
    { title: 'ملح', type: 'unité' },
    { title: 'مكعبات جبنة', type: 'unité' },
    { title: 'مكعبات السكر', type: 'unité' },
    { title: 'مقرونة البانيه (Penne)', type: 'unité' },
    { title: 'معكرونة النودلز', type: 'unité' },
    { title: 'معكرونة القمح الكامل', type: 'unité' },
    { title: 'معكرونة الفيرميسال (Vermicelle)', type: 'unité' },
    { title: 'معكرونة الفيرميسال', type: 'unité' },
    { title: 'معكرونة التالياتلي', type: 'unité' },
    { title: 'معكرونة', type: 'unité' },
    { title: 'معجون طماطم', type: 'unité' },
    { title: 'مسكربون', type: 'unité' },
    { title: 'مسحوق نجمة اليانسون', type: 'unité' },
    { title: 'مسحوق جوز الهند', type: 'unité' },
    { title: 'مسحوق اليانسون', type: 'unité' },
    { title: 'لوز مرحي', type: 'unité' },
    { title: 'مسحوق الكزبر', type: 'unité' },
    { title: 'مسحوق الكاكاو', type: 'unité' },
    { title: 'مسحوق الكاري', type: 'unité' },
    { title: 'مسحوق القرنفل', type: 'unité' },
    { title: 'مسحوق القرفة', type: 'unité' },
    { title: 'مسحوق الفستق', type: 'unité' },
    { title: 'مسحوق الزنجبيل', type: 'unité' },
    { title: 'مسحوق الجيلاتين (حلال)', type: 'unité' },
    { title: 'مسحوق الجيلاتين', type: 'unité' },
    { title: 'مسحوق البندق', type: 'unité' },
    { title: 'مسحوق اكليل الجبل', type: 'unité' },
    { title: 'مرق اللحم', type: 'unité' },
    { title: 'مرق العجل (bouillon d’agneau)', type: 'unité' },
    { title: 'مرق العجل', type: 'unité' },
    { title: 'مرق الدجاج', type: 'unité' },
    { title: 'مردقوش', type: 'unité' },
    { title: 'مربى فراولة', type: 'unité' },
    { title: 'مربى المشمش', type: 'unité' },
    { title: 'مربى التين', type: 'unité' },
    { title: 'مربى التوت (confiture de framboises)', type: 'unité' },
    { title: 'مربى التوت', type: 'unité' },
    { title: 'مخلل الخيار', type: 'unité' },
    { title: 'مربى البرتقال', type: 'unité' },
    { title: 'محلول الجيلاتين', type: 'unité' },
    { title: 'مايونيز', type: 'unité' },
    { title: 'ماء مغلي', type: 'unité' },
    { title: 'ماء فاتر (دافي)', type: 'unité' },
    { title: 'ماء دافي', type: 'unité' },
    { title: 'ماء ساخن', type: 'unité' },
    { title: 'ماء', type: 'unité' },
    { title: 'ماء زهر البرتقال', type: 'unité' },
    { title: 'ليمون مخلل', type: 'unité' },
    { title: 'ليمون', type: 'unité' },
    { title: 'لوز مهروش', type: 'unité' },
    { title: 'لوز احمر', type: 'unité' },
    { title: 'لوز محمر', type: 'unité' },
    { title: 'لوز', type: 'unité' },
    { title: 'لوز أبيض', type: 'unité' },
    { title: 'للطهي :', type: 'unité' },
    { title: 'للحشو :', type: 'unité' },
    { title: 'للحشي :', type: 'unité' },
    { title: 'للتزيين :', type: 'unité' },
    { title: 'لحمة صدر الدجاج', type: 'unité' },
    { title: 'لحمة خروف', type: 'unité' },
    { title: 'لحمة الحبار', type: 'unité' },
    { title: 'لحمة المرقاز', type: 'unité' },
    { title: 'لحمة التونة', type: 'unité' },
    { title: 'لحم مقطع', type: 'unité' },
    { title: 'لحم مفروم', type: 'unité' },
    { title: 'لحم بقر', type: 'unité' },
    { title: 'لحم دجاج', type: 'unité' },
    { title: 'لحم العجل', type: 'unité' },
    { title: 'لحم التونة', type: 'unité' },
    { title: 'لتحضير 250 غ عجينة الفستق منزلية :', type: 'unité' },
    { title: 'لب الفراولة (عصير 100%)', type: 'unité' },
    { title: 'لبن (لبن العيران)', type: 'unité' },
    { title: 'لب الفراولة', type: 'unité' },
    { title: 'كيك الموز', type: 'unité' },
    { title: 'كيك (جنواز) فانيليا', type: 'unité' },
    { title: 'كوكيز شوكولاتة', type: 'unité' },
    { title: 'كوكيز', type: 'unité' },
    { title: 'كوسة مقطعة', type: 'unité' },
    { title: 'كوسة متوسطة', type: 'unité' },
    { title: 'كوسة', type: 'unité' },
    { title: 'كوسا صغيرة الحجم', type: 'unité' },
    { title: 'كندر', type: 'unité' },
    { title: 'كوسا', type: 'unité' },
    { title: 'كمون أسود', type: 'unité' },
    { title: 'كندر بوينو', type: 'unité' },
    { title: 'كمون', type: 'unité' },
    { title: 'كفتة اللحم المفروم :', type: 'unité' },
    { title: 'كسكسي', type: 'unité' },
    { title: 'كزبر مهروش', type: 'unité' },
    { title: 'كزبر', type: 'unité' },
    { title: 'كزبر مقطع', type: 'unité' },
    { title: 'كريمة نباتية للخفقان', type: 'unité' },
    { title: 'كريمة للخفقان (Crème à fouetter végétale)', type: 'unité' },
    { title: 'كريمة للخفقان', type: 'unité' },
    { title: 'كريمة للخفقان ( Crème à fouetter )', type: 'unité' },
    { title: 'كريمة طازجة نباتية', type: 'unité' },
    { title: 'كريمة طازجة سائلة', type: 'unité' },
    { title: 'كريمة طازجة للخفقان', type: 'unité' },
    { title: 'كريمة شانتيه بالياسمين', type: 'unité' },
    { title: 'كريمة سائلة', type: 'unité' },
    { title: 'كريمة النعنع :', type: 'unité' },
    { title: 'كريمة الليمون', type: 'unité' },
    { title: 'كريمة الشوكولاتة :', type: 'unité' },
    { title: 'كريمة اللوز :', type: 'unité' },
    { title: 'كريمة الخفقان', type: 'unité' },
    { title: 'كريمة الجبنة :', type: 'unité' },
    { title: 'كريمة الجبن :', type: 'unité' },
    { title: 'كريمة الثوم', type: 'unité' },
    { title: 'كريمة التشيز كيك', type: 'unité' },
    { title: 'كريمة البندق :', type: 'unité' },
    { title: 'كريمة', type: 'unité' },
    { title: 'كريم شانتيه :', type: 'unité' },
    { title: 'كريم شانتيه الشوكولاتة البيضاء', type: 'unité' },
    { title: 'كركم', type: 'unité' },
    { title: 'كراوية', type: 'unité' },
    { title: 'كراوية مرحية', type: 'unité' },
    { title: 'كراميل', type: 'unité' },
    { title: 'كرامبل البندق :', type: 'unité' },
    { title: 'كرات اللحم المفروم :', type: 'unité' },
    { title: 'كرات اللحم :', type: 'unité' },
    { title: 'كتف العجل مقطع', type: 'unité' },
    { title: 'كبدة دجاج', type: 'unité' },
    { title: 'كتشاب', type: 'unité' },
    { title: 'كاتو الفستق :', type: 'unité' },
    { title: 'كاتشاب', type: 'unité' },
    { title: 'قهوة مرحية', type: 'unité' },
    { title: 'قهوة قابلة للذوبان', type: 'unité' },
    { title: 'قهوة الاسبرسو', type: 'unité' },
    { title: 'قليل من', type: 'unité' },
    { title: 'قلب الخرشوف', type: 'unité' },
    { title: 'قطع خبز', type: 'unité' },
    { title: 'قطع خبز برغر', type: 'unité' },
    { title: 'قطع موز', type: 'unité' },
    { title: 'قطع برتقال', type: 'unité' },
    { title: 'قطع الفراولة', type: 'unité' },
    { title: 'قطع الشوكولاته 52 %', type: 'unité' },
    { title: 'قطع البصل الأخضر', type: 'unité' },
    { title: 'قطع السلمون', type: 'unité' },
    { title: 'قشطة طازجة سائلة', type: 'unité' },
    { title: 'قشطة طازجة ( Crème fraîche épaisse )', type: 'unité' },
    { title: 'قشطة طازجة', type: 'unité' },
    { title: 'قشرة الليمون', type: 'unité' },
    { title: 'قشرة برتقال', type: 'unité' },
    { title: 'قشرة ليمون', type: 'unité' },
    { title: 'قشور قارص', type: 'unité' },
    { title: 'قشرة', type: 'unité' },
    { title: 'قشدة طازجة للخفقان', type: 'unité' },
    { title: 'قشدة طازجة ساخنة', type: 'unité' },
    { title: 'قشدة طازجة سائلة ( Crème fraiche )', type: 'unité' },
    { title: 'قشدة طازجة سائلة', type: 'unité' },
    { title: 'قشدة طازجة', type: 'unité' },
    { title: 'قشدة سائلة طازجة', type: 'unité' },
    { title: 'قشدة الطازجة', type: 'unité' },
    { title: 'قريدس مقشرة', type: 'unité' },
    { title: 'قرفة', type: 'unité' },
    { title: 'قاعدة التشيز كيك :', type: 'unité' },
    { title: 'قاعدة البسكويت :', type: 'unité' },
    { title: 'فول سوداني', type: 'unité' },
    { title: 'فيليه سمك الدوراد', type: 'unité' },
    { title: 'فلفل مهروس', type: 'unité' },
    { title: 'فلفل مدخن مهروش', type: 'unité' },
    { title: 'فلفل مجفف مهروش', type: 'unité' },
    { title: 'فلفل مجفف', type: 'unité' },
    { title: 'فلفل رومي أصفر', type: 'unité' },
    { title: 'فلفل رومي برتقالي', type: 'unité' },
    { title: 'فلفل رومي أخضر', type: 'unité' },
    { title: 'فلفل رومي أحمر', type: 'unité' },
    { title: 'فلفل جاف مهروش', type: 'unité' },
    { title: 'فلفل بارد', type: 'unité' },
    { title: 'فلفل الرومي الاصفر', type: 'unité' },
    { title: 'فلفل اخضر', type: 'unité' },
    { title: 'فلفل احمر مهروش', type: 'unité' },
    { title: 'فلفل أسود مهروش', type: 'unité' },
    { title: 'فلفل أخضر', type: 'unité' },
    { title: 'فلفل أحمر مهروش', type: 'unité' },
    { title: 'فلفل أحمر رومي', type: 'unité' },
    { title: 'فلفل أحمر جاف', type: 'unité' },
    { title: 'فلفل', type: 'unité' },
    { title: 'فلفل أحمر', type: 'unité' },
    { title: 'فسدق', type: 'unité' },
    { title: 'فص', type: 'unité' },
    { title: 'فطر', type: 'unité' },
    { title: 'فطر طازج', type: 'unité' },
    { title: 'فستق مهروش', type: 'unité' },
    { title: 'فستق محمر', type: 'unité' },
    { title: 'فستق', type: 'unité' },
    { title: 'فراولة', type: 'unité' },
    { title: 'فخذ دجاج', type: 'unité' },
    { title: 'فخذ الدجاج', type: 'unité' },
    { title: 'فخد دجاج', type: 'unité' },
    { title: 'فجل احمر مبشور', type: 'unité' },
    { title: 'فتيلة لحم السمك', type: 'unité' },
    { title: 'فتيلة سردين', type: 'unité' },
    { title: 'فتات خبز محمص', type: 'unité' },
    { title: 'فتات الخبز (شابلير)', type: 'unité' },
    { title: 'فانيليا', type: 'unité' },
    { title: 'غاناش الشوكولاتة :', type: 'unité' },
    { title: 'عيدان كرفس مقطع', type: 'unité' },
    { title: 'عود قرفة', type: 'unité' },
    { title: 'عنب مجفف', type: 'unité' },
    { title: 'عنب أبيض', type: 'unité' },
    { title: 'عنب أحمر', type: 'unité' },
    { title: 'عصير نصف ليمونة', type: 'unité' },
    { title: 'عصير ليمونة', type: 'unité' },
    { title: 'عصير ليمون', type: 'unité' },
    { title: 'عصير قارص', type: 'unité' },
    { title: 'عصير', type: 'unité' },
    { title: 'عصير البرتقال', type: 'unité' },
    { title: 'عسل', type: 'unité' },
    { title: 'عجينة وافل', type: 'unité' },
    { title: 'عجينة مفتتة باللوز :', type: 'unité' },
    { title: 'عجينة حلوة باللوز :', type: 'unité' },
    { title: 'عجينة بريزي', type: 'unité' },
    { title: 'عجينة تزويق بيضاء و سوداء', type: 'unité' },
    { title: 'عجينة الموز', type: 'unité' },
    { title: 'عجينة اللوز', type: 'unité' },
    { title: 'عجينة الفطير المورق', type: 'unité' },
    { title: 'عجينة الفستق :', type: 'unité' },
    { title: 'عجينة الفستق', type: 'unité' },
    { title: 'عجينة السابليه:', type: 'unité' },
    { title: 'عجينة الخبز', type: 'unité' },
    { title: 'عجينة البيتزا', type: 'unité' },
    { title: 'عجينة البندق :', type: 'unité' },
    { title: 'عجينة البسكويت :', type: 'unité' },
    { title: 'عجينة البريزي', type: 'unité' },
    { title: 'عجينة العجينة الغوفر : ', type: 'unité' },
    { title: 'عجينة مورقة ( Pate feuilletée )', type: 'unité' },
    { title: 'عجين الفطير المورق', type: 'unité' },
    { title: 'عجين الفطر المورق', type: 'unité' },
    { title: 'طماطم مهروشة', type: 'unité' },
    { title: 'عجين التمر', type: 'unité' },
    { title: 'طماطم مهروسة ( Tomate concassée )', type: 'unité' },
    { title: 'طماطم مهروسة', type: 'unité' },
    { title: 'طماطم مقشرة', type: 'unité' },
    { title: 'طماطم معجونة', type: 'unité' },
    { title: 'طماطم مركزة ( Tomate concentrée )', type: 'unité' },
    { title: 'طماطم مركزة', type: 'unité' },
    { title: 'طماطم سوريز ( Tomate Cerise )', type: 'unité' },
    { title: 'طماطم طازجة مقطعة', type: 'unité' },
    { title: 'طماطم طازجة متوسطة', type: 'unité' },
    { title: 'طماطم طازجة', type: 'unité' },
    { title: 'طماطم', type: 'unité' },
    { title: 'طماطم الكرزية', type: 'unité' },
    { title: 'طرخون', type: 'unité' },
    { title: 'طحينة', type: 'unité' },
    { title: 'طحين القمح', type: 'unité' },
    { title: 'طحين البندق والسكر', type: 'unité' },
    { title: 'صوص الليمون :', type: 'unité' },
    { title: 'صوص اللليمون :', type: 'unité' },
    { title: 'صوص اللبن والخيار :', type: 'unité' },
    { title: 'صوص اللبن بالخيار', type: 'unité' },
    { title: 'صوص الكراميل', type: 'unité' },
    { title: 'صوص السلطة :', type: 'unité' },
    { title: 'صوص الجبن الكريمي:', type: 'unité' },
    { title: 'صلصة حارة', type: 'unité' },
    { title: 'صلصة المايونيز', type: 'unité' },
    { title: 'صلصة المايوناز', type: 'unité' },
    { title: 'صلصة الكراميل :', type: 'unité' },
    { title: 'صلصة الفانيليا :', type: 'unité' },
    { title: 'صلصة العسل :', type: 'unité' },
    { title: 'صلصة الطماطم (المارينارا ):', type: 'unité' },
    { title: 'صلصة الصويا', type: 'unité' },
    { title: 'صلصة الشوكولاتة :', type: 'unité' },
    { title: 'صلصة الشكولاتة :', type: 'unité' },
    { title: 'صلصة السلطة :', type: 'unité' },
    { title: 'صلصة الزبادي :', type: 'unité' },
    { title: 'صلصة التشيلي', type: 'unité' },
    { title: 'صلصة التزويق :', type: 'unité' },
    { title: 'صلصة البيستو بالطماطم المجففة :', type: 'unité' },
    { title: 'صلصة البيستو الجاهزة', type: 'unité' },
    { title: 'صلصة البيستو', type: 'unité' },
    { title: 'صلصة البيتزا', type: 'unité' },
    { title: 'صلصة الباربكيو', type: 'unité' },
    { title: 'اصفر العضم', type: 'unité' },
    { title: 'صدر الدجاجة', type: 'unité' },
    { title: 'صدر الدجاج', type: 'unité' },
    { title: 'شوكولاتة مبشورة', type: 'unité' },
    { title: 'شوكولاتة مبروشة', type: 'unité' },
    { title: 'شوكولاتة عادية', type: 'unité' },
    { title: 'شوكولاتة سوداء 72%', type: 'unité' },
    { title: 'شوكولاتة سوداء', type: 'unité' },
    { title: 'شوكولاتة بيضاء', type: 'unité' },
    { title: 'شوكولاتة 72%', type: 'unité' },
    { title: 'شوكولاتة', type: 'unité' },
    { title: 'شكلاطة بيضة', type: 'unité' },
    { title: 'شكلاطة بالحليب', type: 'unité' },
    { title: 'شكولاتة عادية', type: 'unité' },
    { title: 'شكولاتة سوداء', type: 'unité' },
    { title: 'الشكولاتة المبروشة', type: 'unité' },
    { title: 'شكلاطة كحلة', type: 'unité' },
    { title: 'slice جبن', type: 'unité' },
    { title: 'شراب الكاكاو :', type: 'unité' },
    { title: 'شرائح لوز', type: 'unité' },
    { title: 'شرائح ليمون', type: 'unité' },
    { title: 'شرائح لحم الرمستاك', type: 'unité' },
    { title: 'شرائح لحم البقر', type: 'unité' },
    { title: 'شرائح فلفل أخضر', type: 'unité' },
    { title: 'شرائح فلفل أحمر', type: 'unité' },
    { title: 'شرائح صدر الدجاج', type: 'unité' },
    { title: 'شرائح بطاطا', type: 'unité' },
    { title: 'شرائح جامبون ديك رومي', type: 'unité' },
    { title: 'شرائح بصل', type: 'unité' },
    { title: 'شرائح برتقال', type: 'unité' },
    { title: 'شرائح الليمون المخلل', type: 'unité' },
    { title: 'شرائح الليمون', type: 'unité' },
    { title: 'شرائح اللوز', type: 'unité' },
    { title: 'شرائح الفطر', type: 'unité' },
    { title: 'شرائح الفراولة', type: 'unité' },
    { title: 'شرائح الطماطم المجففة المقطعة ( Tomates séchées hachées )', type: 'unité' },
    { title: 'شرائح الطماطم المجففة ( Tomates séchées )', type: 'unité' },
    { title: 'شرائح الطماطم المجففة', type: 'unité' },
    { title: 'شرائح الزيتون', type: 'unité' },
    { title: 'شرائح الدجاج', type: 'unité' },
    { title: 'شرائح الخيار', type: 'unité' },
    { title: 'شرائح الخبز', type: 'unité' },
    { title: 'شرائح الجبن', type: 'unité' },
    { title: 'شرائح جامبون الدجاج', type: 'unité' },
    { title: 'شرائح الثوم', type: 'unité' },
    { title: 'شرائح الجامبون', type: 'unité' },
    { title: 'شرائح البصل', type: 'unité' },
    { title: 'شرائح البرتقال', type: 'unité' },
    { title: 'شرائح الانشوة', type: 'unité' },
    { title: 'شرائح الاناناس', type: 'unité' },
    { title: 'شبت مقطع', type: 'unité' },
    { title: 'شرائح الأنشوجة', type: 'unité' },
    { title: 'شاي الياسمين', type: 'unité' },
    { title: 'سمك الدوار', type: 'unité' },
    { title: 'سلطة', type: 'unité' },
    { title: 'سكر فانيليا', type: 'unité' },
    { title: 'سكر محور ( Sucre glace )', type: 'unité' },
    { title: 'سكر بودرة', type: 'unité' },
    { title: 'سردين', type: 'unité' },
    { title: 'سكر', type: 'unité' },
    { title: 'سكر CandyS', type: 'unité' },
    { title: 'سكر بني', type: 'unité' },
    { title: 'ستيك اللحم', type: 'unité' },
    { title: 'سبانخ', type: 'unité' },
    { title: 'سباغيتي', type: 'unité' },
    { title: 'زيتون بنفسجي', type: 'unité' },
    { title: 'زيتون أسود', type: 'unité' },
    { title: 'زيتون أخضر', type: 'unité' },
    { title: 'زيتون', type: 'unité' },
    { title: 'زيت نباتي نجمة', type: 'unité' },
    { title: 'زيت نباتي', type: 'unité' },
    { title: 'زيت للقليان نجمة', type: 'unité' },
    { title: 'زيت للقليان', type: 'unité' },
    { title: 'زيت عباد الشمس نجمة', type: 'unité' },
    { title: 'زيت عباد الشمس', type: 'unité' },
    { title: 'زيت زيتون', type: 'unité' },
    { title: 'زيت السمسم', type: 'unité' },
    { title: 'زيت الذرة نجمة', type: 'unité' },
    { title: 'زيت الزيتون', type: 'unité' },
    { title: 'زيت', type: 'unité' },
    { title: 'زيت الذرة', type: 'unité' },
    { title: 'زنجبيل مطبوخ', type: 'unité' },
    { title: 'زنجبيل مقطع', type: 'unité' },
    { title: "زنجبيل مقشر ومقطع", type: "unité" },
    { title: "زعتر مجفف", type: "unité" },
    { title: "زعفران ( Safran )", type: "unité" },
    { title: "زعتر جاف", type: "unité" },
    { title: "زعتر", type: "unité" },
    { title: "زبدة ذائبة", type: "unité" },
    { title: "زبدة الفول السوداني", type: "unité" },
    { title: "زبدة", type: "unité" },
    { title: "زبادي(ياغورت) طبيعي حلو", type: "unité" },
    { title: "زبادي طبيعية ( Yaourt )", type: "unité" },
    { title: "زبادي طبيعية", type: "unité" },
    { title: "زبادي طبيعة ( ياغورت طبيعي )", type: "unité" },
    { title: "زبادي (ياغورت) طبيعي حلو", type: "unité" },
    { title: "ريحان مجفف", type: "unité" },
    { title: "رقائق القمح المقرمشة", type: "unité" },
    { title: "رقائق الشوكولاتة", type: "unité" },
    { title: "رقائق الشكلاطة السوداء", type: "unité" },
    { title: "رقائق الشكلاطة ", type: "unité" },
    { title: "رقائق الشكولاتة", type: "unité" },
    { title: "رقائق الذرة", type: "unité" },
    { title: "ذرة", type: "unité" },
    { title: "رقائق الخبز", type: "unité" },
    { title: "دكواز الفستق :", type: "unité" },
    { title: "دقيق القمح الكامل ( فارينة بالقمح الكامل )", type: "unité" },
    { title: "دقيق القمح الكامل ( فارينة )", type: "unité" },
    { title: "دقيق القمح الكامل", type: "unité" },
    { title: "فارينة ", type: "unité" },
    { title: "دقيق القمح", type: "unité" },
    { title: "دجاج", type: "unité" },
    { title: "خيار مقطع", type: "unité" },
    { title: "خيار مقشر", type: "unité" },
    { title: "خيار صغير", type: "unité" },
    { title: "خيار مخلل", type: "unité" },
    { title: "خيار", type: "unité" },
    { title: "خوخ مقطع", type: "unité" },
    { title: "خوخ مجفف", type: "unité" },
    { title: "خوخ النكتارين", type: "unité" },
    { title: "خوخ ", type: "unité" },
    { title: "خميرة مرطبات", type: "unité" },
    { title: "خميرة فورية للخبز", type: "unité" },
    { title: "خميرة فورية", type: "unité" },
    { title: "خميرة خبز فورية (Levure séche pour pain)", type: "unité" },
    { title: "خميرة خبز فورية ( Levure sèche )", type: "unité" },
    { title: "خميرة خبز فورية", type: "unité" },
    { title: "خميرة حلويات ( Levure chimique )", type: "unité" },
    { title: "خميرة حلويات", type: "unité" },
    { title: "خميرة المرطبات", type: "unité" },
    { title: "خميرة الخبز الفورية", type: "unité" },
    { title: "خميرة الخبز", type: "unité" },
    { title: "خميرة الحلويات", type: "unité" },
    { title: "خميرة", type: "unité" },
    { title: "خليط الكعكة :", type: "unité" },
    { title: "خليط الفراولة :", type: "unité" },
    { title: "خليط الجبن الكريمي :", type: "unité" },
    { title: "خليط البرتقال :", type: "unité" },
    { title: "خلاصة الفانيليا", type: "unité" },
    { title: "خل تفاح", type: "unité" },
    { title: "خل بلسمي", type: "unité" },
    { title: "خل العنب الأحمر", type: "unité" },
    { title: "خل التفاح", type: "unité" },
    { title: "خل البلسمي", type: "unité" },
    { title: "خل", type: "unité" },
    { title: "خل أبيض", type: "unité" },
    { title: "خل أحمر", type: "unité" },
    { title: "خس رومي", type: "unité" },
    { title: "خس روماني", type: "unité" },
    { title: "خس", type: "unité" },
    { title: "خرشوف", type: "unité" },
    { title: "خردل (موستاردا)", type: "unité" },
    { title: "خردل (مستردة)", type: "unité" },
    { title: "خردل (حبوب)", type: "unité" },
    { title: "خردل", type: "unité" },
    { title: "خردل (Moutarde)", type: "unité" },
    { title: "خبز بائت", type: "unité" },
    { title: "خبز الهمبرجر", type: "unité" },
    { title: "خبز التورتيلا", type: "unité" },
    { title: "خبز البريوش", type: "unité" },
    { title: "خبز البرغر", type: "unité" },
    { title: "خبز", type: "unité" },
    { title: "خبز أبيض", type: "unité" },
    { title: "حوت السردين", type: "unité" },
    { title: "حوت السردين المصبر", type: "unité" },
    { title: "حمص منقوع (منفخ )", type: "unité" },
    { title: "حمص مسلوق ( طايب )", type: "unité" },
    { title: "حمص مسلوق", type: "unité" },
    { title: "حمص", type: "unité" },
    { title: "حليب نصف دسم", type: "unité" },
    { title: "حليب مركز حلو", type: "unité" },
    { title: "حليب مركز ( lait concentré )", type: "unité" },
    { title: "حليب مركز", type: "unité" },
    { title: "حليب دسم (كامل)", type: "unité" },
    { title: "حليب دافي", type: "unité" },
    { title: "حليب دسم", type: "unité" },
    { title: "حليب اللوز", type: "unité" },
    { title: "حليب أو ماء", type: "unité" },
    { title: "حليب", type: "unité" },
    { title: "حلوة سمارتيز", type: "unité" },
    { title: "حلوة الكرمال", type: "unité" },
    { title: "حلوة الشامية", type: "unité" },
    { title: "حشوة الدجاج:", type: "unité" },
    { title: "حشو السوفليه :", type: "unité" },
    { title: "حشو الخضار :", type: "unité" },
    { title: "حبيبات الشوكولاتة", type: "unité" },
    { title: "حبيبات الشكلاطة ", type: "unité" },
    { title: "حبق مقطع", type: "unité" },
    { title: "حبق مجفف", type: "unité" },
    { title: "حبق جاف", type: "unité" },
    { title: "حبق", type: "unité" },
    { title: "حبق (ريحان)", type: "unité" },
    { title: "حبار البحر منظف", type: "unité" },
    { title: "حبات من الكبار", type: "unité" },
    { title: "حبات سمسم", type: "unité" },
    { title: "حبات بذور القرع", type: "unité" },
    { title: "حبات الكزبر", type: "unité" },
    { title: "حبات الكبار", type: "unité" },
    { title: "حبات الصنوبر", type: "unité" },
    { title: "حبات M & M ‘ S", type: "unité" },
    { title: "حباة الكبار", type: "unité" },
    { title: "حب الملوك (كرز) محلى", type: "unité" },
    { title: "جيلي أو مربى التوت", type: "unité" },
    { title: "جيلاتين", type: "unité" },
    { title: "جوزة الطيب", type: "unité" },
    { title: "جوز مهروش ( Noix concassée )", type: "unité" },
    { title: "جوز مهروش", type: "unité" },
    { title: "جوز كامل", type: "unité" },
    { title: "جوز الكاجو المهروش", type: "unité" },
    { title: "جوز الكاجو", type: "unité" },
    { title: "جوز الطيب", type: "unité" },
    { title: "جوز", type: "unité" },
    { title: "جنواز الفانيليا :", type: "unité" },
    { title: "جمبون لحم بقري", type: "unité" },
    { title: "جمبون ديك رومي", type: "unité" },
    { title: "جلوكوز", type: "unité" },
    { title: "جلبانة (بازلاء)", type: "unité" },
    { title: "جزر مقطع", type: "unité" },
    { title: "جزر متوسط", type: "unité" },
    { title: "جزر مبروش", type: "unité" },
    { title: "جزر", type: "unité" },
    { title: "جبنة بيضاء", type: "unité" },
    { title: "جبنة بالقشدة", type: "unité" },
    { title: "جبنة الريكوتا", type: "unité" },
    { title: "جبنة الريقوتا", type: "unité" },
    { title: "جبن مبشور", type: "unité" },
    { title: "جبن كريمي", type: "unité" },
    { title: "جبن غرويير", type: "unité" },
    { title: "جبن سيسيليان", type: "unité" },
    { title: "جبن جودا مبشور", type: "unité" },
    { title: "جبن الموزاريلا ( mozzarella )", type: "unité" },
    { title: "جبن الماعز", type: "unité" },
    { title: "جبن الكريمي", type: "unité" },
    { title: "جبن الفيتا", type: "unité" },
    { title: "جبن الفتا ( Fromage feta )", type: "unité" },
    { title: "جبن الشيدر ( Fromage cheddar )", type: "unité" },
    { title: "جبن الريكوتا", type: "unité" },
    { title: "جبن الجودا", type: "unité" },
    { title: "جبن الجريار", type: "unité" },
    { title: "جبن البرميجانو ( Parmesan )", type: "unité" },
    { title: "جبن البارميجانو", type: "unité" },
    { title: "جبن الامنتال", type: "unité" },
    { title: "جامبون الشوريزو ( لحم الدجاج )", type: "unité" },
    { title: "جامبون الدجاج", type: "unité" },
    { title: "جامبون", type: "unité" },
    { title: "ثوم مقطع", type: "unité" },
    { title: "ثوم مفروم", type: "unité" },
    { title: "ثوم معمر مقطع", type: "unité" },
    { title: "ثوم معمر", type: "unité" },
    { title: "ثوم", type: "unité" },
    { title: "تين", type: "unité" },
    { title: "توت وفراولة", type: "unité" },
    { title: "توت العليق أو الفراولة", type: "unité" },
    { title: "توت", type: "unité" },
    { title: "توابل الخبز الحلو", type: "unité" },
    { title: "توابل", type: "unité" },
    { title: "تن", type: "unité" },
    { title: "تمر", type: "unité" },
    { title: "تفاح مقطع", type: "unité" },
    { title: "تفاح مقشر ومقطع", type: "unité" },
    { title: "تفاح", type: "unité" },
    { title: "تسقية الكيك :", type: "unité" },
    { title: "تتبيلة الدجاج :", type: "unité" },
    { title: "تابوناد زيتون", type: "unité" },
    { title: "بيكاربونات الصوديوم", type: "unité" },
    { title: "بيكاربونات الصودا", type: "unité" },
    { title: "بيضة مخلوطة", type: "unité" },
    { title: "بيضة كبيرة", type: "unité" },
    { title: "بيضة طازجة مخلوطة", type: "unité" },
    { title: "بيضة طازجة", type: "unité" },
    { title: "عضمة", type: "unité" },
    { title: "بيض مسلوق", type: "unité" },
    { title: "بيض طازج مخلوط", type: "unité" },
    { title: "بيض طازج", type: "unité" },
    { title: "عضم", type: "unité" },
    { title: "ابيض العضم", type: "unité" },
    { title: "بودرة اللوز", type: "unité" },
    { title: "بودرة الكاكاو", type: "unité" },
    { title: "بودرة البندق", type: "unité" },
    { title: "بندق مهروش", type: "unité" },
    { title: "بندق مهروس", type: "unité" },
    { title: "بندق محمص", type: "unité" },
    { title: "بندق", type: "unité" },
    { title: "بلح البحر", type: "unité" },
    { title: "بقدونس مقطع", type: "unité" },
    { title: "بقدونس مفرومة", type: "unité" },
    { title: "بقدونس مفروم", type: "unité" },
    { title: "بقدونس", type: "unité" },
    { title: "بطاطس مهروسة", type: "unité" },
    { title: "بطاطس مسلوقة", type: "unité" },
    { title: "بطاطس متوسطة مسلوقة", type: "unité" },
    { title: "بطاطس مبروشة", type: "unité" },
    { title: "بطاطس صغير الحجم", type: "unité" },
    { title: "بطاطس شيبس", type: "unité" },
    { title: "بطاطس حجم متوسط", type: "unité" },
    { title: "بطاطس", type: "unité" },
    { title: "بطاطا مسلوقة", type: "unité" },
    { title: "بطاطا كبيرة", type: "unité" },
    { title: "بطاطا", type: "unité" },
    { title: "بصلة صغيرة", type: "unité" },
    { title: "بصل مقطع", type: "unité" },
    { title: "بصل مفروم", type: "unité" },
    { title: "بصل احمر مقطع", type: "unité" },
    { title: "بصل أخضر مقطع", type: "unité" },
    { title: "بصل أحمر مقطع", type: "unité" },
    { title: "بصل أحمر", type: "unité" },
    { title: "بصل أبيض", type: "unité" },
    { title: "بصل", type: "unité" },
    { title: "بسكويت هش", type: "unité" },
    { title: "بسكويت مهروش", type: "unité" },
    { title: "بسكويت توك مالح", type: "unité" },
    { title: "بسكويت الشوكولاتة", type: "unité" },
    { title: "بسكويت أوريو", type: "unité" },
    { title: "بسكويت", type: "unité" },
    { title: "برتقال مالطي", type: "unité" },
    { title: "برتقال أحمر", type: "unité" },
    { title: "برتقال", type: "unité" },
    { title: "بازلاء (جلبانة)", type: "unité" },
    { title: "باذنجان", type: "unité" },
    { title: "بابريكا حار", type: "unité" },
    { title: "بابريكا", type: "unité" },
    { title: "اوراق نعناع جديدة", type: "unité" },
    { title: "اوراق الخس", type: "unité" },
    { title: "انجري بيرد", type: "unité" },
    { title: "الميرانغ", type: "unité" },
    { title: "الموس", type: "unité" },
    { title: "المردقوش", type: "unité" },
    { title: "الماء الفاتر", type: "unité" },
    { title: "الماء", type: "unité" },
    { title: "الكيك", type: "unité" },
    { title: "الكوكيز", type: "unité" },
    { title: "الكمون", type: "unité" },
    { title: 'الكفتة ', type: 'unité' },
    { title: 'الكعكة ', type: 'unité' },
    { title: 'الكزبرة', type: 'unité' },
    { title: 'الكريمة المخفوقة ', type: 'unité' },
    { title: 'الكريمة ', type: 'unité' },
    { title: 'الكريم شانتيه ', type: 'unité' },
    { title: 'الكرمبل او الفتات ', type: 'unité' },
    { title: 'القهوة ', type: 'unité' },
    { title: 'القشدة الطازجة', type: 'unité' },
    { title: 'فلفل أكحل ', type: 'unité' },
    { title: 'فلفل أحمر', type: 'unité' },
    { title: 'الفلفل', type: 'unité' },
    { title: 'الفجل', type: 'unité' },
    { title: 'الغاناش (صلصة الشوكولاتة) ', type: 'unité' },
    { title: 'الغاناش ', type: 'unité' },
    { title: 'العجينة بالكاكاو ', type: 'unité' },
    { title: 'العجينة ', type: 'unité' },
    { title: 'العجين ', type: 'unité' },
    { title: 'الطماطم الكرزية', type: 'unité' },
    { title: 'الطرخون', type: 'unité' },
    { title: 'الصلصة الملونة ', type: 'unité' },
    { title: 'الصلصة اللماعة ', type: 'unité' },
    { title: 'الصلصة ', type: 'unité' },
    { title: 'الشعيرية الملونة', type: 'unité' },
    { title: 'الشبت', type: 'unité' },
    { title: 'السلطة ', type: 'unité' },
    { title: 'الزيتون الأسود', type: 'unité' },
    { title: 'الزعتر', type: 'unité' },
    { title: 'الزبدة', type: 'unité' },
    { title: 'الدجاج ', type: 'unité' },
    { title: 'الخل البلسمي ', type: 'unité' },
    { title: 'الخرشوف', type: 'unité' },
    { title: 'الخبز ', type: 'unité' },
    { title: 'الحليب', type: 'unité' },
    { title: 'الحشو ', type: 'unité' },
    { title: 'الحبق', type: 'unité' },
    { title: 'الجنواز بالشوكولاتة ', type: 'unité' },
    { title: 'الجبن الكريمي', type: 'unité' },
    { title: 'الثوم المقطع', type: 'unité' },
    { title: 'التونة', type: 'unité' },
    { title: 'التفاح المكرمل ', type: 'unité' },
    { title: 'التزيين ', type: 'unité' },
    { title: 'التزويق ', type: 'unité' },
    { title: 'التركيب ', type: 'unité' },
    { title: 'البيستو', type: 'unité' },
    { title: 'البندق المكرمل ', type: 'unité' },
    { title: 'البندق المقرمش ', type: 'unité' },
    { title: 'البقدونس', type: 'unité' },
    { title: 'لبسكويت المقرمش ', type: 'unité' },
    { title: 'البسكويت ', type: 'unité' },
    { title: 'البراونيز ', type: 'unité' },
    { title: 'الأفوكادو', type: 'unité' },
    { title: 'اكليل الجبل', type: 'unité' },
    { title: 'ارز', type: 'unité' },
    { title: 'اجاص بالفانيليا ', type: 'unité' },
    { title: 'اجاص', type: 'unité' },
    { title: 'إكليل مهروش', type: 'unité' },
    { title: 'أوراق حبق', type: 'unité' },
    { title: 'أوراق النعناع', type: 'unité' },
    { title: 'أوراق اللازانيا', type: 'unité' },
    { title: 'أوراق الكزبرة', type: 'unité' },
    { title: 'أوراق السبانخ', type: 'unité' },
    { title: 'أوراق الرند', type: 'unité' },
    { title: 'أوراق الخس', type: 'unité' },
    { title: 'أوراق الحبق', type: 'unité' },
    { title: 'أوراق المعدنوس', type: 'unité' },
    { title: 'أوراق الاكليل', type: 'unité' },
    { title: 'أناناس', type: 'unité' },
    { title: 'أعواد البريدزال', type: 'unité' },
    { title: 'أصابع الموزاريلا', type: 'unité' },
    { title: 'أريغانو', type: 'unité' },
    { title: 'أرز مطبوخ', type: 'unité' },
    { title: 'Nutella', type: 'unité' },
    { title: 'لإكليل', type: 'unité' },
    { title: 'حبات البافو', type: 'unité' },
    { title: 'خبز الباغيت', type: 'unité' },
    { title: 'كريمة السبيكيلوس', type: 'unité' },
    { title: 'بنجر', type: 'unité' },
    { title: 'سمك البار', type: 'unité' },
    { title: 'كراث', type: 'unité' },
    { title: 'كينوا', type: 'unité' },
    { title: 'رمان', type: 'unité' },
    { title: 'الفاصوليا الخضراء', type: 'unité' },
    { title: 'برغل', type: 'unité' },
    { title: 'دجاج مفروم', type: 'unité' },
    { title: 'معكرونة لولبية', type: 'unité' },
    { title: 'دجاج مصلي', type: 'unité' },
    { title: 'جرجير', type: 'unité' },
    { title: 'العدس الاشقر', type: 'unité' },
    { title: 'العدس الأخضر', type: 'unité' },
    { title: 'منّاني', type: 'unité' },
    { title: 'أوراق الفيرفيان', type: 'unité' },
    { title: 'عطر اللوز المر', type: 'unité' },
    { title: 'زبيب', type: 'unité' },
    { title: 'فاصوليا ملسوقة', type: 'unité' },
    { title: 'سمك الوارطة', type: 'unité' },
    { title: 'ليمون مقشر ', type: 'unité' },
    { title: 'تالياتيلي', type: 'unité' },
    { title: 'أرز', type: 'unité' },
    { title: 'ليم مخلل', type: 'unité' },
    { title: 'يوغرت يوناني طبيعي دليس دانون OIKOS', type: 'unité' },
    { title: 'حبوب القرع', type: 'unité' },
    { title: 'حبوب دوار الشمس', type: 'unité' },
    { title: 'جمبري', type: 'unité' },
    { title: 'زمباع', type: 'unité' },
    { title: 'عصير الرمان', type: 'unité' },
    { title: 'حبات الرمان', type: 'unité' },
    { title: 'سميد', type: 'unité' },
    { title: 'روح اللوز المر', type: 'unité' },
    { title: 'كرمب أحمر', type: 'unité' },
    { title: 'جلجلان مقلي', type: 'unité' },
    { title: 'جبن الكامومبير', type: 'unité' },
    { title: 'حبوب البسباس', type: 'unité' },
    { title: 'بسباس', type: 'unité' },
    { title: 'بروكلو', type: 'unité' },
    { title: 'رأس حانوت', type: 'unité' },
    { title: 'كرافس', type: 'unité' },
    { title: 'تابل', type: 'unité' },
    { title: 'معدنوس', type: 'unité' },
    { title: 'خبز لبناني محمر', type: 'unité' },
    { title: 'جبن الروكفور', type: 'unité' },
    { title: 'عسل ساخن', type: 'unité' },
    { title: 'هروس', type: 'unité' },
    { title: 'كروية', type: 'unité' },
    { title: 'بسكويت السبيكيلوس', type: 'unité' },
    { title: 'محلول قهوة سريعة الذوبان ', type: 'unité' },
    { title: 'فارينة الأرز', type: 'unité' },
    { title: 'بذور الشيا', type: 'unité' },
    { title: 'زريعة الكتان', type: 'unité' },
    { title: 'جبن مسكربون', type: 'unité' },
    { title: 'حبات قهوة', type: 'unité' },
    { title: 'فرمبواز', type: 'unité' },
    { title: 'بوفريوة مهروشة', type: 'unité' },
    { title: 'ملسوقة', type: 'unité' },
    { title: 'كورنفلاكس شوكولاتة', type: 'unité' },
    { title: 'معجون برتقال', type: 'unité' },
    { title: 'كريمة سائلة ساخنة', type: 'unité' },
    { title: 'كورنفلاكس', type: 'unité' },
    { title: 'مشماش', type: 'unité' },
    { title: 'كتف خروف', type: 'unité' },
    { title: 'عوينة شايحة', type: 'unité' },
    { title: 'كبدة خروف', type: 'unité' },
    { title: 'إسكالوب دجاج', type: 'unité' },
    { title: 'كسبرة', type: 'unité' },
    { title: 'حساء الخضار', type: 'unité' },
    { title: 'قشور الليمون المخلل ', type: 'unité' },
    { title: 'معجون البوفريوة', type: 'unité' },
    { title: 'ماء ورد', type: 'unité' },
    { title: 'بوفريوة', type: 'unité' },
    { title: 'عجينة الفسدق', type: 'unité' },
    { title: 'فسدق مرحي', type: 'unité' },
    { title: 'عوينة', type: 'unité' },
    { title: 'شكلاطة للطلي (chocolat à tartiner)', type: 'unité' },
    { title: 'برتقال مجفف', type: 'unité' },
    { title: 'مسحوق البوفريوة', type: 'unité' },
    { title: 'روح النعناع', type: 'unité' },
    { title: 'قرع بوطزينة', type: 'unité' },
    { title: 'طبيخة شعير', type: 'unité' },
    { title: 'بذور عباد الشمس', type: 'unité' },
    { title: 'جلجلان', type: 'unité' },
    { title: 'ماء بارد', type: 'unité' },
    { title: 'موسكادا', type: 'unité' },
    { title: 'مقرونة بلومة', type: 'unité' },
    { title: 'فول مصري', type: 'unité' },
    { title: 'حليب رايب', type: 'unité' },
    { title: 'اللحم الهبرة', type: 'unité' },
    { title: 'لوبيا منفخة', type: 'unité' },
    { title: 'حبوب المستردة', type: 'unité' },
    { title: 'شربة فريك', type: 'unité' },
    { title: 'Brownies Intense Moulin D\'or', type: 'unité' },
    { title: 'موسكدا', type: 'unité' },
    { title: 'دجاجة', type: 'unité' },
    { title: 'سوسيس فرانكفورت', type: 'unité' },
    { title: 'كورنفلاكس القمح', type: 'unité' },
    { title: 'قشور البرتقال', type: 'unité' },
    { title: 'مرق الخضار', type: 'unité' },
    { title: 'شربة لسان عصفور', type: 'unité' },
    { title: 'زبدة الكاكوية', type: 'unité' },
    { title: 'كمبوت التفاح', type: 'unité' },
    { title: 'فارينة الشوفان', type: 'unité' },
    { title: 'قشور الكليمنتين', type: 'unité' },
    { title: 'فلفل حلو', type: 'pièce' },
    { title: 'فلفل حار', type: 'pièce' },
    { title: 'جمبون دجاج', type: 'unité' },
    { title: 'فول منقوع (منفخ)', type: 'unité' },
    { title: 'قرع احمر', type: 'unité' },
    { title: 'قنارية', type: 'pièce' },
    { title: 'كريم فراش', type: 'unité' },
    { title: 'زوزة', type: 'unité' },
    { title: 'محمصة', type: 'unité' },
    { title: 'لحم الداندون', type: 'unité' },
    { title: 'شكلاطة ذايبة', type: 'unité' },
    { title: 'مقرونة مصموطة', type: 'unité' },
    { title: 'مكعب مرق الدجاج', type: 'pièce' },
    { title: 'مكعب مرق الخضرة', type: 'pièce' },
    { title: 'مارغرين', type: 'unité' },
    { title: 'روز مصموط', type: 'unité' },
    { title: 'معجون فراز', type: 'unité' },
    { title: 'كاسيس', type: 'unité' },
    { title: 'كليل وزعتر', type: 'unité' },
    { title: 'شوريزو', type: 'unité' },
    { title: 'حليب مركز (lait concentré) بدون سكر', type: 'unité' },
    { title: 'كاكاوية', type: 'unité' },
    { title: 'جبن تستوري', type: 'pièce' },
    { title: 'كريمة طازجة Crème fraîche', type: 'unité' },
    { title: 'مقرونة', type: 'unité' },
    { title: 'شكلاطة', type: 'unité' },
    { title: 'عصير المادالينا', type: 'unité' },
    { title: 'مادالينا', type: 'unité' },
    { title: 'فلفل بر العبيد', type: 'pièce' },
    { title: 'لوبيا خضراء', type: 'pièce' },
    { title: 'قارص', type: 'unité' },
    { title: 'قشور المادالينا', type: 'unité' },
    { title: 'تابوناد (زيتون مرحي)', type: 'unité' },
    { title: 'ترنجية', type: 'unité' },
    { title: 'كريمة انقليزية (Crème anglaise)', type: 'pièce' },
    { title: 'سينوج', type: 'pièce' },
    { title: 'جبن ازرق', type: 'pièce' },
    { title: 'شمبنيون', type: 'pièce' },
    { title: 'بيتراف', type: 'unité' },
    { title: 'نعناع شايح', type: 'unité' },
    { title: 'صوص الطماطم', type: 'unité' },
    { title: 'سميد أرطب', type: 'pièce' },
    { title: 'سلق', type: 'unité' },
    { title: 'هريسة عربي', type: 'pièce' },
    { title: 'ورق الفيلو (filo)', type: 'unité' },
    { title: 'عضم السمان', type: 'pièce' },
    { title: 'هيل مرحي', type: 'pièce' },
    { title: 'معجون مشماش', type: 'pièce' },
    { title: 'قارص مصير', type: 'unité' },
    { title: 'فقوص', type: 'unité' },
    { title: 'فلفل مهروش', type: 'unité' },
    { title: 'فراز', type: 'unité' },
    { title: 'ماء زهر', type: 'unité' },
    { title: 'شعير', type: 'unité' },
    { title: 'مقرونة كاملة', type: 'unité' },
    { title: 'جبن ادام (Edam)', type: 'unité' },
    { title: 'توت بري (myrtille)', type: 'unité' }

]
