export const tools = [
    {id:"1",name:"مقلاة",is_active:"Active"},
    {id:"2",name:"صحن",is_active:"Active"},
    {id:"3",name:" طبق ",is_active:"Active"},
    {id:"4",name:"القدر",is_active:"Active"},
    {id:"5",name:"سكين",is_active:"Active"},
    {id:"6",name:"شوكة",is_active:"Active"},
    {id:"7",name:" ملعقة",is_active:"Active"},
    {id:"8",name:"صحفة",is_active:"Active"},
    {id:"9",name:"الخلاط الكهربائي",is_active:"Active"},
    {id:"10",name:"قالب",is_active:"Active"},
    {id:"11",name:"كأس زجاجي",is_active:"Active"},
    {id:"12",name:"شواية",is_active:"Active"},
    {id:"13",name:"أعواد خشبية",is_active:"Active"},
    {id:"14",name:"خلاط",is_active:"Active"},
    {id:"15",name:"قالب التارت",is_active:"Active"},
    {id:"16",name:"طبق الفور",is_active:"Active"},
    {id:"17",name:"كؤوس",is_active:"Active"},
    {id:"18",name:"الأسياخ الخشبية",is_active:"Active"},
    {id:"19",name:"قلقال",is_active:"Active"},
    {id:"20",name:"كيس",is_active:"Active"},
    {id:"21",name:"خفاقة يدوية",is_active:"Active"},
    {id:"22",name:"ملعقة خشبية",is_active:"Active"},
    {id:"23",name:"كاسارونة",is_active:"Active"},
    {id:"24",name:"وعاء معدني",is_active:"Active"},
    {id:"25",name:"الخفاقة الكهربائية",is_active:"Active"},
    {id:"27",name:"أوعية رامكنز ",is_active:"Active"},
    {id:"28",name:"قالب دائري",is_active:"Active"},
    {id:"29",name:"قوالب الكاب كيك",is_active:"Active"},
    {id:"30",name:"قالب مربع",is_active:"Active"},
    {id:"31",name:"قالب الدونات",is_active:"Active"},
    {id:"32",name:"سكين حلويات",is_active:"Active"},
    {id:"33",name:"مصفات",is_active:"Active"},
    {id:"34",name:"قوالب السيليكون",is_active:"Active"},
    {id:"35",name:"الاشكال",is_active:"Active"},
    {id:"36",name:"كيس حلواني",is_active:"Active"},
    {id:"37",name:"ثلاثة قوالب",is_active:"Active"},
    {id:"38",name:"قالب ورقي",is_active:"Active"},
    {id:"39",name:"قالب مستطيل",is_active:"Active"},
    {id:"40",name:"القطاعة",is_active:"Active"},
    {id:"41",name:"طبق فرن",is_active:"Active"},
    {id:"42",name:"الاكواب",is_active:"Active"},
    {id:"43",name:"وعاء خزفي",is_active:"Active"},
    {id:"44",name:"قوالب التارت الصغيرة",is_active:"Active"},
    {id:"45",name:"قوالب دائرية صغيرة",is_active:"Active"},
    {id:"46",name:"الأوعية الورقية",is_active:"Active"},
    {id:"47",name:"الأوعية",is_active:"Active"},
    {id:"48",name:"أوعية زجاجية",is_active:"Active"},
    {id:"49",name:"قالب كايك (طول 25 سم)",is_active:"Inactive"},
    {id:"50",name:"قالب دائري (قطر 20 سم)",is_active:"Inactive"},
    {id:"51",name:"قالب دائري (قطر 25 سم)",is_active:"Inactive"},
    {id:"52",name:"قالب مربع (16 سم)\t",is_active:"Inactive"},
    {id:"53",name:"قالب مربع (20 سم)\t",is_active:"Inactive"},
    {id:"54",name:"قالب مستطيل (24*16 سم)\t",is_active:"Inactive"},
    {id:"55",name:"قالب دائري (قطر 22 سم)\t",is_active:"Inactive"}
    ]
    