import { Tajawal } from "next/font/google";
import "./globals.css";

const tajawal = Tajawal({
   subsets: ["latin"],
   weight: ["200", "300", "400", "500", "700", "800", "900"]
  });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  icons: {
    type: 'image/svg',
    icon: '/logo.svg',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={tajawal.className}>{children}</body>
    </html>
  );
}
