

import Button from "@/components/Button";
import prisma from "@/lib/db";

export default function Home() {


  async function addUnit() {
    "use server"

    const tags = [
      { title: 'خبز بيتا', type: 'unité' },
      { title: 'بطيخ', type: 'unité' },
      { title: 'بذور الشمر', type: 'unité' },
      { title: 'سمك أبو سيف', type: 'unité' },
      { title: 'الثلج المسحوق', type: 'unité' },
      { title: 'لفت', type: 'unité' },
      { title: 'الماء المثلج', type: 'unité' },
      { title: 'الشاي الأخضر العادي', type: 'unité' },
      { title: 'سمك السردين', type: 'unité' },
      { title: 'قرع', type: 'unité' },
      { title: 'شوفان', type: 'unité' },
      { title: 'مشمش', type: 'unité' },
      { title: 'بروكلي', type: 'unité' },
      { title: 'معكرونة أصداف', type: 'unité' },
      { title: 'بذور شيا', type: 'unité' },
      { title: 'بذور اليقطين المحمص', type: 'unité' },
      { title: 'اليقطين', type: 'unité' },
      { title: 'العدس الأحمر', type: 'unité' },
      { title: 'كوريزو', type: 'unité' },
      { title: 'حبات الهيل', type: 'pièce' },
      { title: 'شوكولاتة سوداء مبشورة', type: 'unité' },
      { title: 'أوراق البريك', type: 'unité' },
      { title: 'مرقاز', type: 'unité' },
      { title: 'نصف رأس ثوم', type: 'unité' },
      { title: 'موس بالشوكولاتة السوداء', type: 'unité' },
      { title: 'نجمة اليانسون', type: 'unité' },
      { title: 'نشاء', type: 'unité' },
      { title: 'نعناع مفروم', type: 'unité' },
      { title: 'نعناع مقطع', type: 'unité' },
      { title: 'نوتيلا', type: 'unité' },
      { title: 'هريسة', type: 'unité' },
      { title: 'هريسة ناظور الوطن القبلي', type: 'unité' },
      { title: 'ورق الحبق', type: 'unité' },
      { title: 'ورق نعناع مقطع', type: 'unité' },
      { title: 'ورق الغار', type: 'unité' },
      { title: 'ورقة سبناخ', type: 'unité' },
      { title: 'ورقة خس', type: 'unité' },
      { title: 'ياغورط طبيعي', type: 'unité' },
      { title: 'موس بالشوكولاتة', type: 'unité' },
      { title: 'موس بالشوكولاتة البيضاء', type: 'unité' },
      { title: 'موس النوتيلا', type: 'unité' },
      { title: 'موس الكاكاو', type: 'unité' },
      { title: 'موس الفستق', type: 'unité' },
      { title: 'موس الفانيليا', type: 'unité' },
      { title: 'موس الزبادي', type: 'unité' },
      { title: 'موس الشوكولاتة', type: 'unité' },
      { title: 'موس الجبن الكريمي', type: 'unité' },
      { title: 'موز', type: 'unité' },
      { title: 'منتج CandyS', type: 'unité' },
      { title: 'ملون غذائي', type: 'unité' },
      { title: 'ملفوف أحمر', type: 'unité' },
      { title: 'ملفوف أبيض', type: 'unité' },
      { title: 'ملح خشين', type: 'unité' },
      { title: 'ملح', type: 'unité' },
      { title: 'مكعبات جبنة', type: 'unité' },
      { title: 'مكعبات السكر', type: 'unité' },
      { title: 'مقرونة البانيه (Penne)', type: 'unité' },
      { title: 'معكرونة النودلز', type: 'unité' },
      { title: 'معكرونة القمح الكامل', type: 'unité' },
      { title: 'معكرونة الفيرميسال (Vermicelle)', type: 'unité' },
      { title: 'معكرونة الفيرميسال', type: 'unité' },
      { title: 'معكرونة التالياتلي', type: 'unité' },
      { title: 'معكرونة', type: 'unité' },
      { title: 'معجون طماطم', type: 'unité' },
      { title: 'مسكربون', type: 'unité' },
      { title: 'مسحوق نجمة اليانسون', type: 'unité' },
      { title: 'مسحوق جوز الهند', type: 'unité' },
      { title: 'مسحوق اليانسون', type: 'unité' },
      { title: 'لوز مرحي', type: 'unité' },
      { title: 'مسحوق الكزبر', type: 'unité' },
      { title: 'مسحوق الكاكاو', type: 'unité' },
      { title: 'مسحوق الكاري', type: 'unité' },
      { title: 'مسحوق القرنفل', type: 'unité' },
      { title: 'مسحوق القرفة', type: 'unité' },
      { title: 'مسحوق الفستق', type: 'unité' },
      { title: 'مسحوق الزنجبيل', type: 'unité' },
      { title: 'مسحوق الجيلاتين (حلال)', type: 'unité' },
      { title: 'مسحوق الجيلاتين', type: 'unité' },
      { title: 'مسحوق البندق', type: 'unité' },
      { title: 'مسحوق اكليل الجبل', type: 'unité' },
      { title: 'مرق اللحم', type: 'unité' },
      { title: 'مرق العجل (bouillon d’agneau)', type: 'unité' },
      { title: 'مرق العجل', type: 'unité' },
      { title: 'مرق الدجاج', type: 'unité' },
      { title: 'مردقوش', type: 'unité' },
      { title: 'مربى فراولة', type: 'unité' },
      { title: 'مربى المشمش', type: 'unité' },
      { title: 'مربى التين', type: 'unité' },
      { title: 'مربى التوت (confiture de framboises)', type: 'unité' },
      { title: 'مربى التوت', type: 'unité' },
      { title: 'مخلل الخيار', type: 'unité' },
      { title: 'مربى البرتقال', type: 'unité' },
      { title: 'محلول الجيلاتين', type: 'unité' },
      { title: 'مايونيز', type: 'unité' },
      { title: 'ماء مغلي', type: 'unité' },
      { title: 'ماء فاتر (دافي)', type: 'unité' },
      { title: 'ماء دافي', type: 'unité' },
      { title: 'ماء ساخن', type: 'unité' },
      { title: 'ماء', type: 'unité' },
      { title: 'ماء زهر البرتقال', type: 'unité' },
      { title: 'ليمون مخلل', type: 'unité' },
      { title: 'ليمون', type: 'unité' },
      { title: 'لوز مهروش', type: 'unité' },
      { title: 'لوز احمر', type: 'unité' },
      { title: 'لوز محمر', type: 'unité' },
      { title: 'لوز', type: 'unité' },
      { title: 'لوز أبيض', type: 'unité' },
      { title: 'للطهي :', type: 'unité' },
      { title: 'للحشو :', type: 'unité' },
      { title: 'للحشي :', type: 'unité' },
      { title: 'للتزيين :', type: 'unité' },
      { title: 'لحمة صدر الدجاج', type: 'unité' },
        { title: 'لحمة خروف', type: 'unité' },
        { title: 'لحمة الحبار', type: 'unité' },
        { title: 'لحمة المرقاز', type: 'unité' },
        { title: 'لحمة التونة', type: 'unité' },
        { title: 'لحم مقطع', type: 'unité' },
        { title: 'لحم مفروم', type: 'unité' },
        { title: 'لحم بقر', type: 'unité' },
        { title: 'لحم دجاج', type: 'unité' },
        { title: 'لحم العجل', type: 'unité' },
        { title: 'لحم التونة', type: 'unité' },
        { title: 'لتحضير 250 غ عجينة الفستق منزلية :', type: 'unité' },
        { title: 'لب الفراولة (عصير 100%)', type: 'unité' },
        { title: 'لبن (لبن العيران)', type: 'unité' },
        { title: 'لب الفراولة', type: 'unité' },
        { title: 'كيك الموز', type: 'unité' },
        { title: 'كيك (جنواز) فانيليا', type: 'unité' },
        { title: 'كوكيز شوكولاتة', type: 'unité' },
        { title: 'كوكيز', type: 'unité' },
        { title: 'كوسة مقطعة', type: 'unité' },
        { title: 'كوسة متوسطة', type: 'unité' },
        { title: 'كوسة', type: 'unité' },
        { title: 'كوسا صغيرة الحجم', type: 'unité' },
        { title: 'كندر', type: 'unité' },
        { title: 'كوسا', type: 'unité' },
        { title: 'كمون أسود', type: 'unité' },
        { title: 'كندر بوينو', type: 'unité' },
        { title: 'كمون', type: 'unité' },
        { title: 'كفتة اللحم المفروم :', type: 'unité' },
        { title: 'كسكسي', type: 'unité' },
        { title: 'كزبر مهروش', type: 'unité' },
        { title: 'كزبر', type: 'unité' },
        { title: 'كزبر مقطع', type: 'unité' },
        { title: 'كريمة نباتية للخفقان', type: 'unité' },
        { title: 'كريمة للخفقان (Crème à fouetter végétale)', type: 'unité' },
        { title: 'كريمة للخفقان', type: 'unité' },
        { title: 'كريمة للخفقان ( Crème à fouetter )', type: 'unité' },
        { title: 'كريمة طازجة نباتية', type: 'unité' },
        { title: 'كريمة طازجة سائلة', type: 'unité' },
        { title: 'كريمة طازجة للخفقان', type: 'unité' },
        { title: 'كريمة شانتيه بالياسمين', type: 'unité' },
        { title: 'كريمة سائلة', type: 'unité' },
        { title: 'كريمة النعنع :', type: 'unité' },
        { title: 'كريمة الليمون', type: 'unité' },
        { title: 'كريمة الشوكولاتة :', type: 'unité' },
        { title: 'كريمة اللوز :', type: 'unité' },
        { title: 'كريمة الخفقان', type: 'unité' },
        { title: 'كريمة الجبنة :', type: 'unité' },
        { title: 'كريمة الجبن :', type: 'unité' },
        { title: 'كريمة الثوم', type: 'unité' },
        { title: 'كريمة التشيز كيك', type: 'unité' },
        { title: 'كريمة البندق :', type: 'unité' },
        { title: 'كريمة', type: 'unité' },
        { title: 'كريم شانتيه :', type: 'unité' },
        { title: 'كريم شانتيه الشوكولاتة البيضاء', type: 'unité' },
        { title: 'كركم', type: 'unité' },
        { title: 'كراوية', type: 'unité' },
        { title: 'كراوية مرحية', type: 'unité' },
        { title: 'كراميل', type: 'unité' },
        { title: 'كرامبل البندق :', type: 'unité' },
        { title: 'كرات اللحم المفروم :', type: 'unité' },
        { title: 'كرات اللحم :', type: 'unité' },
        { title: 'كتف العجل مقطع', type: 'unité' },
        { title: 'كبدة دجاج', type: 'unité' },
        { title: 'كتشاب', type: 'unité' },
        { title: 'كاتو الفستق :', type: 'unité' },
        { title: 'كاتشاب', type: 'unité' },
        { title: 'قهوة مرحية', type: 'unité' },
        { title: 'قهوة قابلة للذوبان', type: 'unité' },
        { title: 'قهوة الاسبرسو', type: 'unité' },
        { title: 'قليل من', type: 'unité' },
        { title: 'قلب الخرشوف', type: 'unité' },
        { title: 'قطع خبز', type: 'unité' },
        { title: 'قطع خبز برغر', type: 'unité' },
        { title: 'قطع موز', type: 'unité' },
        { title: 'قطع برتقال', type: 'unité' },
        { title: 'قطع الفراولة', type: 'unité' },
        { title: 'قطع الشوكولاته 52 %', type: 'unité' },
        { title: 'قطع البصل الأخضر', type: 'unité' },
        { title: 'قطع السلمون', type: 'unité' },
        { title: 'قشطة طازجة سائلة', type: 'unité' },
        { title: 'قشطة طازجة ( Crème fraîche épaisse )', type: 'unité' }
         
    ];
  

    try {
      const result = await prisma.ingredients.createMany({
        data : tags
      })
      // const result = await prisma.tags.deleteMany({})
    
      console.log(`Inserted ${result.count} ingredients`);
    } catch (error) {
      console.log(error)
    }
  }
  



  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      HOME
  <Button addUnit={addUnit} className='border p-2' />
    </main>
  );
}
